### ISSUE TITLE
Album Covers and Favorites 

### ISSUE THREAD

**Issue by DirtyOldMan66** [LusciousMedia/luscious#13]
Across the site, it appears as though album covers in the picture communities have been changed to whatever image was last uploaded into the album. 

Also, the displayed number of "likes" for a picture album is now displayed as the total number of likes for all images within that album. For example. instead of a picture album showing 75 album likes, it might be displayed as 4,000 album likes (the number of combined likes for every image within the album).

**Comment by KaySackey** [comment]
This is part of the new algorithm for counting likes. I'll make a posting about it soon.
