### ISSUE TITLE
Site Chat is down

### ISSUE THREAD

**Issue by AereonLus** [LusciousMedia/luscious#2]
I know that many members appreciate and miss the site chat. Is it possible to start it again? I know that it apparently doesn't restart when it shuts down and this is what creates the issue in the first place.

**Comment by KaySackey** [comment]
I keep restarting it twice a day, but it goes down in the interim. This isn't a long term solution.

I've built in some debugging for the server, so I should get some data back on *why* it is crashing and be able to fix it at the source.

**Comment by AereonLus** [comment]
Do you have fixed times ( or windows) when you restart the chat, so people can use it for the time it's being up?

**Comment by KaySackey** [comment]
Generally, I restart it it whenever I login to work for the day. So 7PM GMT. I also check on it around the end of the day, at 3AM GMT. It's not totally a fixed schedule though.

Current system is written in Python, using TornadIO, which is old and deprecated.

I want to move onto a new server, self-written in Elixir: https://github.com/KaySackey/magpie-client

And a new client written with ReactJS:  https://github.com/KaySackey/magpie-client

Both are open source, which may... maybe, help with stability if everyone can take a look at the code.

**Comment by KaySackey** [comment]
Chat is back up again, with a new daemonization process so it should be more stable.

**Comment by KaySackey** [comment]
This has been fixed.
