### ISSUE TITLE
Resizing crop in avatar screen

### ISSUE THREAD

**Issue by Queen-Calamity** [LusciousMedia/luscious#20]
Got an issue with display on the lines for cropping avatars, it shows no indication of dimensions while stretching however the field itself is still resizable after stretching and can be interacted with through the symbols for changing dimension just fine (pointy arrows.) The display for the selected area is still translated into the image preview field. It appears to be layering the visual for the crop beneath the image field. If you could take a look at it when you could, that would be neato.
Thanks in advance.

**Comment by KaySackey** [comment]
This should be fixed now.
