### ISSUE TITLE
"Edit Picture" Feature Not Working Properly When Trying to Delete Images

### ISSUE THREAD

**Issue by DirtyOldMan66** [LusciousMedia/luscious#25]
When I try to delete a duplicate image, I've always selected the "edit picture" option and then clicked on the images I want to get rid of (which creates a yellow border around each selected pic). That no longer seems to work, and clicking an image in the "edit picture" screen has no effect. 

Pics can still be deleted one at a time by viewing them image and then selecting the delete option, but the above method was often more convenient (especially when needing to get rid of multiple images).

**Comment by KaySackey** [comment]
Thanks for the report. This is going to get fixed today, when I push the new changeset.
