### ISSUE TITLE
Duplicate Image Filter Doesn't Seem as Effective

### ISSUE THREAD

**Issue by DirtyOldMan66** [LusciousMedia/luscious#26]
Perhaps it's just a one-time thing, but I uploaded a picture album tonight and noticed that four different duplicate images were able to get past the filter (it caught one). In the past, it seemed to catch duplicates at a much higher rate.

**Comment by KaySackey** [comment]
Could it be that the pictures weren't actually duplicates? If its even a minor change to the file---like the meta data is changed by your OS before sending the image, then it shows up as a totally different picture on our end.

**Comment by DirtyOldMan66** [comment]
Not sure. They looked like duplicates to me. If it happens again, I'll pay even closer attention and let you know.
