### ISSUE TITLE
Issue: Can't remove users from blocked list

### ISSUE THREAD

**Issue by CrackedMC** [LusciousMedia/luscious#29]
I am unable to remove some users i added to my block list beacuse i wrote the names wrong and now they're permanently blocked (what i didn't want ) everytime i try to remove them i just redirected to a seit (ttps://members.luscious.net/user-blocklist/edit_members/#) # means i tried to unblock'em but it didn't work

**Comment by KaySackey** [comment]
Try it again right now. I've pushed a patch.

-------
K. Sackey
Cloud Nine

**Comment by DirtyOldMan66** [comment]
The user who started this thread has been banned from the site, so feel free to close it whenever you want. They won't be back to do it themselves.

**Comment by KaySackey** [comment]
Oh well then.
