### ISSUE TITLE
Trouble Editing Members on PM Groups

### ISSUE THREAD

**Issue by DirtyOldMan66** [LusciousMedia/luscious#30]
I tried to edit out one of the mods from the mod thread after they abruptly retired. After I clicked the "x" next to their name and selected the save options, I eventually got this message just above the list of names:

"An unknown error has occurred"

The user is question is currently listed as Faceless Man, as he has de-activated his account.

**Comment by KaySackey** [comment]
From my checking, if you try to remove a Faceless Man, it *will* remove the user but for a currently unknown reason it returned an error in your case. I haven't been able to reproduce it in a testing environment though, so I am thinking it may be something specific to that users' account, or just the fact that we had so many people on that single mod thread.
