### ISSUE TITLE
"Follow" Button Not Visible to User

### ISSUE THREAD

**Issue by DirtyOldMan66** [LusciousMedia/luscious#31]
A new member of the site contacted me and mentioned that the "follow" button wasn't visible to them the various profile pages. They sent along the following screen capture: http://imgur.com/BX395Uw

**Comment by KaySackey** [comment]
That persons issue is likely that they're using Adblock or Ghostery, and its blocking 'social media icons'. It thinks that any follow button is a 'social media icon'.

**Comment by DirtyOldMan66** [comment]
Thanks for the reply. I'll notify the individual.
