### ISSUE TITLE
Broken Images/Thumbnails

### ISSUE THREAD

**Issue by DirtyOldMan66** [LusciousMedia/luscious#7]
Tried to upload a couple of albums late Tuesday night. Everything appeared to work fine. However, once the upload was processed for each image, a broken thumbnail appeared on the page. I waited a while and checked back, and the full-size version of all the images were also broken, I eventually deleted the album, but I can only assume that the problem remains.

**Comment by Exiagan** [comment]
Yeah, Broken pics and Thumbnails are here even when I tried an hour later, not just a 404, but a complete crash of the luscious page. Later, after I encounter the issue I had to close the webpage in order to load the old pics that weren't effected by bug.

**Comment by KaySackey** [comment]
There was a misconfiguration on the upload server. It should be fixed now. I tested it.

I did however have to delete ~3000 pictures which were uploaded unsucessfully yesterday.
